version: "2"

run:
  timeout: 5m
  tests: true
  go: '1.24.0'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

issues:
  exclude-dirs:
    - internal/swagger
    - gen
  max-issues-per-linter: 0
  max-same-issues: 0
